name: degust_et_des_couleurs
description: Appli de dégustation de restaurant.

publish_to: 'none'

version: 1.4.0+6

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  path_provider_foundation: ^2.2.3
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  flutter_typeahead: ^5.0.1
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  email_validator: ^2.1.16
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_cache_manager: ^3.3.1
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
    - assets/images/tasting_1.jpeg
    - assets/images/tasting_2.jpeg
    - assets/images/tasting_3.jpeg
    - assets/images/tasting_4.jpeg
